- https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml
- https://www.washingtonpost.com/rss
- https://www.marketwatch.com/rss/topstories
- https://feeds.a.dj.com/rss/RSSMarketsMain.xml
- https://www.cnbc.com/id/100003114/device/rss/rss.html
- https://www.sciencedaily.com/rss/top/science.xml
- https://www.nature.com/feeds/news.rss
- https://news.ycombinator.com/rss
- https://spectrum.ieee.org/rss
- https://techcrunch.com/rss
- https://www.noahpinion.blog/feed
- https://gwern.net/rss
- https://paulkedrosky.com/rss
- https://feeds.feedblitz.com/marginalrevolution
- https://www.strangeloopcanon.com/feed
- https://apnews.com/rss
- https://www.bbc.com/rss
- https://www.buzzfeednews.com/rss
- https://www.cbc.ca/rss
- https://www.cnbc.com/rss
- https://www.economist.com/rss
- https://www.npr.org/rss
- https://www.nytimes.com/rss
- https://www.marketwatch.com/rss
- https://www.quantamagazine.org/rss
- https://www.sciencedaily.com/rss
- https://www.sciencenews.org/rss
- https://www.smithsonianmag.com/rss
- https://blog.jgc.org/rss
- https://blog.jonudell.net/rss
- https://cdss.berkeley.edu/rss
- https://colab.research.google.com/rss
- https://eprint.iacr.org/rss
- https://english.elpais.com/rss
- https://news.samsung.com/rss
