# List of RSS or HTTP source URLs to ingest (one per line).
# High-quality sources for financial, economic, scientific, and geopolitical insights.

# Major news outlets
- https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml

# Financial & economics  
- https://www.marketwatch.com/rss/topstories
- https://feeds.a.dj.com/rss/RSSMarketsMain.xml
- https://www.cnbc.com/id/100003114/device/rss/rss.html

# Science & technology
- https://www.sciencedaily.com/rss/top/science.xml
- https://news.ycombinator.com/rss
- https://spectrum.ieee.org/rss
- https://techcrunch.com/rss

# High-quality blogs and analysis
- https://www.noahpinion.blog/feed
- https://gwern.net/rss
- https://paulkedrosky.com/rss
- https://feeds.feedblitz.com/marginalrevolution
- https://www.strangeloopcanon.com/feed
