# Curated list of high-signal RSS/Atom feeds used by the Foresight Forge
# pipeline. Non-relevant, low-quality, or duplicate sources have been removed.

- https://www.noahpinion.blog/feed
- https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml
- https://www.marketwatch.com/rss/topstories
- https://feeds.a.dj.com/rss/RSSMarketsMain.xml
- https://www.cnbc.com/id/100003114/device/rss/rss.html
- https://www.sciencedaily.com/rss/top/science.xml
- https://www.nature.com/feeds/news.rss
- https://news.ycombinator.com/rss
- https://apnews.com/rss
- https://archaeologymag.com/rss
- https://data4democracy.substack.com/rss
- https://forgecode.dev/rss
- https://gwern.net/rss
- https://machinelearning.apple.com/rss
- https://openai.com/rss
- https://paulkedrosky.com/rss
- https://spectrum.ieee.org/rss
- https://techcrunch.com/rss
- https://worldhistory.substack.com/rss
- https://www.bbc.com/rss
- https://www.cbc.ca/rss
- https://www.cnbc.com/rss
- https://www.esa.int/rss
- https://www.fastcompany.com/rss
- https://www.ibm.com/rss
- https://www.npr.org/rss
- https://www.nytimes.com/rss
- https://www.quantamagazine.org/rss
- https://www.sciencenews.org/rss
- https://www.smithsonianmag.com/rss
- https://www.taipeitimes.com/rss
- https://www.the-independent.com/rss
- https://www.washingtonpost.com/rss
- https://www.ycombinator.com/rss
- https://www.strangeloopcanon.com/feed
- https://feeds.feedblitz.com/marginalrevolution
