- https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml
- https://www.marketwatch.com/rss/topstories
- https://feeds.a.dj.com/rss/RSSMarketsMain.xml
- https://www.cnbc.com/id/100003114/device/rss/rss.html
- https://www.sciencedaily.com/rss/top/science.xml
- https://news.ycombinator.com/rss
- https://spectrum.ieee.org/rss
- https://techcrunch.com/rss
- https://www.noahpinion.blog/feed
- https://gwern.net/rss
- https://paulkedrosky.com/rss
- https://feeds.feedblitz.com/marginalrevolution
- https://www.strangeloopcanon.com/feed
- https://apnews.com/rss
- https://blog.jgc.org/rss
- https://blog.jonudell.net/rss
- https://colab.research.google.com/rss
- https://english.elpais.com/rss
- https://quantamagazine.org/rss
- https://www.bbc.com/rss
- https://www.buzzfeednews.com/rss
- https://www.cbc.ca/rss
- https://www.cnbc.com/rss
- https://www.economist.com/rss
- https://www.nasa.gov/rss
- https://www.npr.org/rss
- https://www.nytimes.com/rss
- https://www.sciencedaily.com/rss
- https://www.sciencenews.org/rss
- https://www.washingtonpost.com/rss
- www.cbc.ca
- www.cnbc.com
- www.marketwatch.com
- www.nytimes.com
- www.theguardian.com
- www.wired.com
- www.cbc.ca/rss
- www.cnbc.com/rss
- www.marketwatch.com/rss
- www.nytimes.com/rss
- www.theguardian.com/rss
- www.wired.com/rss
- https://www.federalreserve.gov/feeds/press_all.xml
- https://www.federalreserve.gov/feeds/press_monetary.xml
- https://home.treasury.gov/news/press-releases?format=rss
- https://www.conference-board.org/rss/economy/economy_all.xml
- https://www.mba.org/news-and-research/research-and-economics/single-family-research/weekly-applications-survey?format=rss
- https://apps.bea.gov/rss/rss.xml
- https://www.eia.gov/todayinenergy/rss.php
- https://www.bls.gov/feed/empsit.rss
- https://www.bls.gov/feed/cpi.rss
- https://www.bls.gov/feed/ppi.rss
- https://www.bls.gov/feed/eci.rss
- https://www.bls.gov/feed/jolts.rss
- https://www.bls.gov/feed/prod2.rss
- https://www.bls.gov/feed/realer.rss
- https://www.census.gov/economic-indicators/indicator.xml
- https://www.federalreserve.gov/feeds/g17.xml
- https://www.federalreserve.gov/feeds/g19.xml
- https://www.federalreserve.gov/feeds/h8.xml
- https://www.federalreserve.gov/feeds/h15.xml
- https://www.federalreserve.gov/feeds/z1.xml
